language: perl
sudo: false

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

services:
  - mysql

install:
  - cpanm --notest --quiet Dist::Zilla
  - cpanm DBD::mysql@4.033
  - cpanm --notest Test::mysqld
  - cpanm --notest DBIx::Class::InflateColumn::Serializer
  - cpanm --notest Net::EmptyPort
  - cpanm --notest DBIx::Class::Schema::Loader
  - cpanm --notest DateTime::Format::SQLite
  - cpanm --notest DateTime::Format::MySQL
  - cpanm --notest SQL::Translator
  - dzil authordeps | cpanm --quiet --notest
  - cpanm --quiet --notest --installdeps .

script:
  - dzil test
