language: perl
sudo: true

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - sudo apt-get install mysqld

install:
  - cpanm --notest --quiet Dist::Zilla
  - cpanm --notest Test::mysqld
  - cpanm --notest DBIx::Class::InflateColumn::Serializer
  - dzil authordeps | cpanm --quiet --notest
  - cpanm --quiet --notest --installdeps .

script:
  - dzil test
